// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoH4tu2YTwU0CD2TsdCxrPTAYwfCdwqrk',
    appId: '1:602985908259:web:87af1cf2bffc818ed14996',
    messagingSenderId: '602985908259',
    projectId: 'depi-2bdb6',
    authDomain: 'depi-2bdb6.firebaseapp.com',
    storageBucket: 'depi-2bdb6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvzETSetAoF0REfQLs-WnU8fFsuCR8n88',
    appId: '1:602985908259:android:2fdbd2d290c04ca0d14996',
    messagingSenderId: '602985908259',
    projectId: 'depi-2bdb6',
    storageBucket: 'depi-2bdb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOSHSvxdLeyqlFD2BYIAMhIbuSNEcLr3A',
    appId: '1:602985908259:ios:03a8685a52f5dbfad14996',
    messagingSenderId: '602985908259',
    projectId: 'depi-2bdb6',
    storageBucket: 'depi-2bdb6.firebasestorage.app',
    iosBundleId: 'com.example.depiTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOSHSvxdLeyqlFD2BYIAMhIbuSNEcLr3A',
    appId: '1:602985908259:ios:03a8685a52f5dbfad14996',
    messagingSenderId: '602985908259',
    projectId: 'depi-2bdb6',
    storageBucket: 'depi-2bdb6.firebasestorage.app',
    iosBundleId: 'com.example.depiTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoH4tu2YTwU0CD2TsdCxrPTAYwfCdwqrk',
    appId: '1:602985908259:web:7c817a4b974e2ca9d14996',
    messagingSenderId: '602985908259',
    projectId: 'depi-2bdb6',
    authDomain: 'depi-2bdb6.firebaseapp.com',
    storageBucket: 'depi-2bdb6.firebasestorage.app',
  );
}
