// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfISiU_6gM931k1phLXFkZMhpBNNH3M3I',
    appId: '1:31775963057:web:45c9c57f4ccd7db6712f90',
    messagingSenderId: '31775963057',
    projectId: 'depi-task',
    authDomain: 'depi-task.firebaseapp.com',
    storageBucket: 'depi-task.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6gEmnfJ-nz3O7xx-_u-7Xc-VgxX-tf10',
    appId: '1:31775963057:android:373c6df7eb060c31712f90',
    messagingSenderId: '31775963057',
    projectId: 'depi-task',
    storageBucket: 'depi-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA3j2M5kpxC5gihW8_Mt3RMiCx5MCPjjE',
    appId: '1:31775963057:ios:05c7b700019eebbf712f90',
    messagingSenderId: '31775963057',
    projectId: 'depi-task',
    storageBucket: 'depi-task.firebasestorage.app',
    iosBundleId: 'com.example.depiTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA3j2M5kpxC5gihW8_Mt3RMiCx5MCPjjE',
    appId: '1:31775963057:ios:05c7b700019eebbf712f90',
    messagingSenderId: '31775963057',
    projectId: 'depi-task',
    storageBucket: 'depi-task.firebasestorage.app',
    iosBundleId: 'com.example.depiTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfISiU_6gM931k1phLXFkZMhpBNNH3M3I',
    appId: '1:31775963057:web:2fbf837f91693aaa712f90',
    messagingSenderId: '31775963057',
    projectId: 'depi-task',
    authDomain: 'depi-task.firebaseapp.com',
    storageBucket: 'depi-task.firebasestorage.app',
  );

}